# AKANE CONFIGURATION FILE
# Copyright (C) 2025-2026 Axeon Network. Developed by KitSixtyFour and AveryEclipse.


# == BASIC INFORMATION ==
# The full name of your wiki
name: Axeon KuroWiki

# The name of your wiki
title: KuroWiki

# used for debug, to be hard-coded for Kuro STBL
productname: "Axeon Akane Code Name \"Cairo\""

# The author of the wiki
author: Axeon Network

# Copyright year(s)
copyyear: "2025-2026"

# The text used in embeds, like Discord.
description: "Axeon KuroWiki Release Candidate"

# Self-explanatory
url: https://axeon-network.github.io

# The path to be used if Deltari is deployed to a sub-directory and
# NOT the server root. This is optional
baseurl: /kurowiki

# URL of the site's source code
sourceurl: "https://github.com/Axeon-Network/kurowiki"

# The name of the license your wiki is licensed under.
license: "Creative Commons Attribution-ShareAlike 4.0 International"
# The URL of the license.
licenseurl: https://creativecommons.org/licenses/by-sa/4.0/deed.en
# Short license name, self-explanatory
license-s: CC-BY-SA-4.0

# The name of the license the wiki's images are licensed under.
img_license: Creative Commons Attribution 4.0 International
# Ditto; Line 39
img_licenseurl: https://creativecommons.org/licenses/by/4.0/deed.en
# Ditto; Line 41
img_license-s: CC-BY-4.0


# == HOMEPAGE ==
# A quick description of your wiki and what is it about, visible on the homepage.
home_desc: "This is the home page for KuroWiki. An online encyclopedia about the Axeon Network and its administrators (KitSixtyFour and AveryEclipse)."

# The file name of the article to be used in the Featured Article card.
featuredarticle: winnishilecat


# DEPRECATED
# retail tag. specifies the version number used in the drawer, and is to be replaced by
# an incrementing one IF the debug mode is enabled.
# retailtag: 7.0.4477.private/mdelta_N.260222-2026


# == DEVELOPER & DEBUG ==
# The phase of Delta/Kuro's development track.
devphase: Release Candidate
# Short version, used in drawer if nedecesary
devphase-s: Silver Release
# ID for dev builds
idprefix: "rc1" # Release Candidate 1

# = Debug Mode =
# Enables various developer features of Deltari, like the watermarks and
# "(Debug)" suffix to the drawer.
debug: true
# = Private Build =
# Similar to Microsoft Windows, self-explanatory
privatebuild: false
# = Extended Build Lab =
# Shows the branch and timestamp of the build, instead of the major, minor
# and build number
buildlabex: true
# = Build Delta =
# Enables or disables build revisions, useful when build numbers are fixed
builddelta: false

# = Retail Mode =
# Self-explanatory, used for public releases
retail: false

# stupid
myvariable: "{{ site.myvariable }}"


# == APPEARANCE AND PERSONALIZATION ==
# Windows 7 reference frfr

# = Accent Everywhere =
# Specifies if the Material Design Lite components should use the accent color or not
accent-everywhere: true

# = Custom Background =
# Specifies whether to use a custom background instead of the retail ones, light and dark
# variants are supported!

# Leave blank to use defaults.
background-dark:
background-light:

# = Drawer =
# Specifies if the site title should be used in the drawer, like MDL does by default.
drawertitle: false
# Specifies if a banner image should be used in the drawer, in place of the site title.
# You can drop your own banner over at /res/img/banner.png!
drawerbanner: true

# only ONE of these can be enabled
# ...i mean you can use both, but that wouldnt be practical, would it?
# if you enable neither, you need help


# == DEFAULTS ==
# So we can save a lot of time writing in the stupid front-matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "material"
  -
    scope:
      type: "media"
    values:
      layout: "file"
  -
    scope:
      type: "articles" # "type", not "path". very funny
    values:
      layout: "material"
  -
    scope:
      type: "special" # i like boys anyway -sfox64
    values:
      layout: "material"
  -
    scope:
      path: "special"
      type: "special"
    values:
      layout: "material"

collections:
  files:
    output: true
    permalink: "./File::name"
  articles:
    output: true # the fuck you mean you actually need this
  special:
    output: true # jekyll you can fuck my ass whenever you want, fuck you.
  featured:
    output: true
  news:
    output: true
    permalink: "./Document::slug"


# == OTHER ==
# liquid you son of a bitch
encoding: "utf-8"

markdown_ext: "markdown,mkdown,mkdn,mkd,md,mk"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate-v2
  # "jekyll-make-this-work" ahh names lmfao

pagination:
  enabled: true

kramdown:
  input: GFM
  hard_wrap: true

exclude:
  # - res/ruby/version # just so it doesnt get caught in a loop
  # - res/ruby/buildtag # ditto
  # - res/ruby/delta # ditto
  - _includes/misc/version.html # what res/ruby/version used to do when excluded, except its more better.