require 'time'
require 'jekyll'
require 'etc' 
require 'fileutils'

# version number config
major = 7
minor = 0

# tracker to prevent double banners
$axeon_banner_shown = false

Jekyll::Hooks.register :site, :after_init do |site|
  unless $axeon_banner_shown
    dev_phase = site.config['devphase'] || "Developer Release"
    
    if site.config['debug'] == true
      type = "(Checked)"
    end
    if site.config['retail'] == true
      type = "(Retail)"
    end

    puts "Axeon Akane Engine #{dev_phase} #{type} [Version #{major}.#{minor}]"
    puts "               (C) 2025-2026 Axeon Network. All Rights Reserved.\n\n"
    puts "Panther Version Master Utility [Version 4.0.5200]"
    puts "               (C) 2025-2026 KitSixtyFour/StupidBiFox.\n\n"
    puts ""
    puts "WARNING!!!: Panther does NOT write to buildtag nor version. Instead, it writes to _includes/version.html"
    puts "            for accessibility use. Please update any old definitions"
    puts ""
    $axeon_banner_shown = true
  end
end

Jekyll::Hooks.register :site, :after_reset do |site|
  header_dir = File.expand_path('_includes', site.source)
  version_header_path = File.join(header_dir, 'version.html')

  FileUtils.mkdir_p(header_dir) unless File.directory?(header_dir)

  # build lab
  lab = ''
  begin
    lab = `git rev-parse --abbrev-ref HEAD`.strip
    raise if lab.empty? || lab.include?("fatal")
  rescue
    date_stub = Time.now.strftime("%y-%m-%d")
    user_stub = ENV['USERNAME'] || ENV['USER'] || Etc.getlogin || "dummy"
    lab = "#{date_stub}_#{user_stub}"
  end

  if site.config['privatebuild'] == true
    current_user = ENV['USERNAME'] || ENV['USER'] || Etc.getlogin || "dummy"
    lab = "private/#{lab}(#{current_user})"
  end

  # ids
  is_debug = site.config['debug'] == true
  delta_enabled = site.config['builddelta'] == true
  id_prefix = site.config['idprefix'] || "dp"
  id_suffix = is_debug ? "chk" : "fre"
  id = "#{id_prefix}#{id_suffix}"

  begin
    stored_number = 5200
  rescue
    stored_number = 5200
  end

  begin
    delta_nbr = 1
  rescue
    delta_nbr = 0
  end

  current_delta = delta_nbr
  current_incremental_number = 5200
  buildtag = ""

  if delta_enabled && is_debug
    current_delta += 1
  else
    current_delta = 0
  end

#  if is_debug
#    current_incremental_number += 0 # disable this for now.
#    File.write(build_number_file_path, current_incremental_number.to_s)
    
#    timestamp = Time.now.strftime("%y%m%d-%H%M")
#    buildtag = "#{major}.#{minor}.#{current_incremental_number}.#{current_delta}.#{id}.#{lab}.#{timestamp}"
#   File.write(build_tag_file_path, buildtag)
    
#   Jekyll.logger.info "PANTHER:", "Loading Akn #{current_incremental_number}.#{current_delta}.#{lab}.#{timestamp}"
# else
#   if File.exist?(build_tag_file_path)
#     saved_tag = File.read(build_tag_file_path).strip
#     parts = saved_tag.split('.')
      
      # grab the build number (index 2) and timestamp (last index)
#      current_incremental_number = parts[2] || stored_number
#      saved_timestamp = parts.last || "000000-0000"

      # reconstruct the string with the LIVE ID (fre) and Lab
#      buildtag = "#{major}.#{minor}.#{current_incremental_number}.#{current_delta}.#{id}.#{lab}.#{saved_timestamp}"
#      File.write(build_tag_file_path, buildtag)
#    else
#      buildtag = "#{major}.#{minor}.#{stored_number}.#{current_delta}.#{id}.#{lab}.000000-0000"
#    end
#  end

  # Extract final timestamp string safely
  final_timestamp = buildtag.split('.').last

  # site configuration fallback
  site.config['version'] = {
    'major' => major,
    'minor' => minor,
    'id' => id,
    'build' => current_incremental_number,
    'delta' => current_delta,
    'lab' => lab,
    'timestamp' => final_timestamp,
    'full' => buildtag
  }

  # make a header
  header_content = <<~HTML
    <!-- AkanePanther Header -->
    <!-- This file is automatically generated by Panther on each build -->
    <!-- If you see nothing when seeing this file on InspElement, that's fine!! :) -->
    {% assign AKN_MAJOR = #{major} %}
    {% assign AKN_MINOR = #{minor} %}
    {% assign AKN_BUILD = #{current_incremental_number} %}
    {% assign AKN_DELTA = #{current_delta} %}
    {% assign AKN_ID = "#{id}" %}
    {% assign AKN_LAB = "#{lab}" %}
    {% assign AKN_TIMESTAMP = "#{final_timestamp}" %}
    {% assign AKN_VERSION = "#{buildtag}" %}
  HTML

  File.write(version_header_path, header_content)
end