name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main # the branch displaying on public kurowiki itself
      - nekori64 # branch where the actual coding happens
      - kayaurora # another branch where other actual coding happens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read base version
        id: base
        run: echo "base=$(cat VERSION)" >> $GITHUB_OUTPUT # this reads the actual kurowiki version actually put in kurowiki itself

      - name: Generate version string
        id: version
        run: |
          branch=${GITHUB_REF_NAME}
          timestamp=$(date -u +'%y%m%d-%H%M')
          echo "full=${{ steps.base.outputs.base }}.${branch}.${timestamp}" >> $GITHUB_OUTPUT
   # where:
       # "branch=${GITHUB_REF_NAME}" is the branch the code is pushed to 
       # "timestamp=$(date -u +'%y%m%d-%H%M')" generates the date & time, where:
          # %y = 25 (current year)
          # %m = 09 (current month)
          # %d = 06 (current day)
          # %H = 01 (current hour)
          # %M = 53 (current minute)
       # "echo "full=${{ steps.base.outputs.base }}.${branch}.${timestamp}" >> $GITHUB_OUTPUT" basically merges it all and generates the actual string as for e.g. "1.0.main.250906-0153"

      - name: Build with Jekyll
        run: |
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build \
            --config _config.yml \
            --destination _site \
            --config <(echo "version: ${{ steps.version.outputs.full }}")
# the version string generated by gh actions is then reported as the version in the jekyll config which then shows on the actual kurowiki

      - name: Deploy to GitHub Pages (only main branch)
        if: github.ref_name == 'main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_sitename: Build and Deploy Jekyll